### ISSUE TITLE
Captcha 502

### ISSUE THREAD

**Issue by makorne** [Cassielxd/cassie_admin#1]
Hi!

Thank you for great projects!

But something went wrong with login:

![Cassie_502_Screenshot_2023-04-26_11-16-21](https://user-images.githubusercontent.com/26540498/234469205-c1771e79-aa53-472e-821c-a70b02e29d98.png)

What versions of node needed for build this project?
I tried several unsuccessfully.

**Comment by Cassielxd** [comment]
Thank you for your attention. The server is ready



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cassielxd/cassie_admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 中午12:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cassielxd/cassie_admin] Captcha 502 (Issue #1)





 
Hi!
 
Thank you for great projects!
 
But something went wrong with login:
 

 
What versions of node needed for build this project?
 I tried several unsuccessfully.

**Comment by makorne** [comment]
Thank you for fast fix!

But what versions of node needed for build this project?
I tried install cassie_admin with node 16, 18 but get the error:

```
Now using node v16.19.1 (npm v8.19.3)
bash-5.2$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pkcs7@0.2.3',
npm WARN EBADENGINE   required: { npm: '^1.4.6', node: '^0.10' },
npm WARN EBADENGINE   current: { node: 'v16.19.1', npm: '8.19.3' }
npm WARN EBADENGINE }

```
What node version is needed?

**Comment by makorne** [comment]
Of course I tried node: '^0.10' , altogth it very old and has many security issues.
But got another error: 


```
npm run serve

> cassie-admin@3.3.0 serve /home/vue/cassie_admin
> vue-cli-service serve

 INFO  Starting development server...
0% compiling ERROR  TypeError: Cannot set property 'chunkLoading' of undefined
TypeError: Cannot set property 'chunkLoading' of undefined
    at WebWorkerTemplatePlugin.apply (/home/vue/cassie_admin/node_modules/webpack/lib/webworker/WebWorkerTemplatePlugin.js:20:40)
    at Compiler.createChildCompiler (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:561:12)
    at Compilation.createChildCompiler (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Compilation.js:2243:24)
    at /home/vue/cassie_admin/node_modules/monaco-editor-webpack-plugin/out/plugins/AddWorkerEntryPointPlugin.js:16:43
    at AsyncParallelHook.eval [as callAsync] (eval at create (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at AsyncParallelHook.lazyCompileHook (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:669:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:662:28)
    at compiler.hooks.watchRun.callAsync.err (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:41:32)
    at Watching.compiler.readRecords.err (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:33:9)
    at Compiler.readRecords (/home/vue/cassie_admin/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:529:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cassie-admin@3.3.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
```
